#' Alesia
#' 
#' @inheritParams minify
#' 
#' @export 
alesia <- function(
  caseSensitive = FALSE,
  collapseBooleanAttributes = TRUE,
  collapseInlineTagWhitespace = TRUE,
  collapseWhitespace = TRUE,
  conservativeCollapse = TRUE,
  continueOnParseError = TRUE,
  customAttrAssign = list(),
  customAttrSurround = list(),
  decodeEntities = FALSE,
  html5 = TRUE,
  includeAutoGeneratedTags = TRUE,
  keepClosingSlash = FALSE,
  minifyCSS = TRUE,
  minifyJS = TRUE,
  minifyURLs = TRUE,
  preserveLineBreaks = FALSE,
  preventAttributesEscaping = FALSE,
  processConditionalComments = FALSE,
  quoteCharacter = "'",
  removeAttributeQuotes = TRUE,
  removeComments = TRUE,
  removeEmptyAttributes = TRUE,
  removeEmptyElements = FALSE,
  removeOptionalTags = FALSE,
  removeRedundantAttributes = FALSE,
  removeScriptTypeAttributes = FALSE,
  removeStyleLinkTypeAttributes = FALSE,
  sortAttributes = FALSE,
  sortClassName = FALSE,
  trimCustomFragments = FALSE,
  useShortDoctype = FALSE
) {
  args <- as.list(environment())
  \(req, res) {
    res$post_render_hook(make_hook(args))
  }
}

make_hook <- function(
  args
) {
  \(self, content, ext) {
    args$html <- content
    do.call("minify", args)
  }
}