#' Minify
#' 
#' Minify HTML.
#' 
#' @param html                         HTML string to minify.
#' @param caseSensitive                Treat attributes in case sensitive manner (useful for custom HTML tags) | false |
#' @param collapseBooleanAttributes    [Omit attribute values from boolean attributes](http://perfectionkills.com/experimenting-with-html-minifier/#collapse_boolean_attributes) | false |
#' @param collapseInlineTagWhitespace  Don't leave any spaces between display:inline; elements when collapsing. Must be used in conjunction with collapseWhitespace=true | false |
#' @param collapseWhitespace           [Collapse white space that contributes to text nodes in a document tree](http://perfectionkills.com/experimenting-with-html-minifier/#collapse_whitespace) | false |
#' @param conservativeCollapse         Always collapse to 1 space (never remove it entirely). Must be used in conjunction with collapseWhitespace=true | false |
#' @param continueOnParseError         [Handle parse errors](https://html.spec.whatwg.org/multipage/parsing.html#parse-errors) instead of aborting. | false |
#' @param customAttrAssign             Arrays of regex'es that allow to support custom attribute assign expressions (e.g. `<div flex?="{{mode != cover}}"></div>`) | [ ] |
#' @param customAttrSurround           Arrays of regex'es that allow to support custom attribute surround expressions (e.g. `<input {{#if value}}checked="checked"{{/if}}>`) | [ ] |
#' @param decodeEntities               Use direct Unicode characters whenever possible | false |
#' @param html5                        Parse input according to HTML5 specifications | true |
#' @param includeAutoGeneratedTags     Insert tags generated by HTML parser | true |
#' @param keepClosingSlash             Keep the trailing slash on singleton elements | false |
#' @param minifyCSS                    Minify CSS in style elements and style attributes (uses [clean-css](https://github.com/jakubpawlowicz/clean-css)) | false (could be true, Object, Function(text, type)) |
#' @param minifyJS                     Minify JavaScript in script elements and event attributes (uses [UglifyJS](https://github.com/mishoo/UglifyJS2)) | false (could be true, Object, Function(text, inline)) |
#' @param minifyURLs                   Minify URLs in various attributes (uses [relateurl](https://github.com/stevenvachon/relateurl)) | false (could be String, Object, Function(text)) |
#' @param preserveLineBreaks           Always collapse to 1 line break (never remove it entirely) when whitespace between tags include a line break. Must be used in conjunction with collapseWhitespace=true | false |
#' @param preventAttributesEscaping    Prevents the escaping of the values of attributes | false |
#' @param processConditionalComments   Process contents of conditional comments through minifier | false |
#' @param quoteCharacter               Type of quote to use for attribute values (' or ") | |
#' @param removeAttributeQuotes        [Remove quotes around attributes when possible](http://perfectionkills.com/experimenting-with-html-minifier/#remove_attribute_quotes) | false |
#' @param removeComments               [Strip HTML comments](http://perfectionkills.com/experimenting-with-html-minifier/#remove_comments) | false |
#' @param removeEmptyAttributes        [Remove all attributes with whitespace-only values](http://perfectionkills.com/experimenting-with-html-minifier/#remove_empty_or_blank_attributes) | false (could be true, Function(attrName, tag)) |
#' @param removeEmptyElements          [Remove all elements with empty contents](http://perfectionkills.com/experimenting-with-html-minifier/#remove_empty_elements) | false |
#' @param removeOptionalTags           [Remove optional tags](http://perfectionkills.com/experimenting-with-html-minifier/#remove_optional_tags) | false |
#' @param removeRedundantAttributes    [Remove attributes when value matches default.](http://perfectionkills.com/experimenting-with-html-minifier/#remove_redundant_attributes) | false |
#' @param removeScriptTypeAttributes   Remove type="text/javascript" from script tags. Other type attribute values are left intact | false |
#' @param removeStyleLinkTypeAttributes Remove type="text/css" from style and link tags. Other type attribute values are left intact | false |
#' @param sortAttributes               [Sort attributes by frequency](#sorting-attributes--style-classes) | false |
#' @param sortClassName                [Sort style classes by frequency](#sorting-attributes--style-classes) | false |
#' @param trimCustomFragments          Trim white space around ignoreCustomFragments. | false |
#' @param useShortDoctype              [Replaces the doctype with the short (HTML5) doctype](http://perfectionkills.com/experimenting-with-html-minifier/#use_short_doctype) | false |
#' 
#' @export 
minify <- function(
  html,
  caseSensitive = FALSE,
  collapseBooleanAttributes = TRUE,
  collapseInlineTagWhitespace = TRUE,
  collapseWhitespace = TRUE,
  conservativeCollapse = TRUE,
  continueOnParseError = TRUE,
  customAttrAssign = list(),
  customAttrSurround = list(),
  decodeEntities = FALSE,
  html5 = TRUE,
  includeAutoGeneratedTags = TRUE,
  keepClosingSlash = FALSE,
  minifyCSS = TRUE,
  minifyJS = TRUE,
  minifyURLs = TRUE,
  preserveLineBreaks = FALSE,
  preventAttributesEscaping = FALSE,
  processConditionalComments = FALSE,
  quoteCharacter = "'",
  removeAttributeQuotes = TRUE,
  removeComments = TRUE,
  removeEmptyAttributes = TRUE,
  removeEmptyElements = FALSE,
  removeOptionalTags = FALSE,
  removeRedundantAttributes = FALSE,
  removeScriptTypeAttributes = FALSE,
  removeStyleLinkTypeAttributes = FALSE,
  sortAttributes = FALSE,
  sortClassName = FALSE,
  trimCustomFragments = FALSE,
  useShortDoctype = FALSE
) {
  args <- as.list(environment())[-1]
  ct$assign("opts", args)
  ct$assign("html", html)
  ct$eval("require('html-minifier').minify(html, opts)")
}
